project:
  type: website
  output-dir: docs
  
website:
  title: "Briana Allman"
  navbar:
    left:
      - href: index.qmd
        text: About Me
      - projects.qmd
      - resume.qmd
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/brianaallman
      - icon: github
        href: https://github.com/briallman/briallman.github.io
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Briana Allman"

format:
  html:
    theme: lux
    toc: true

editor: source

