---
title: "Education"
---

<p style="margin-top: 20px;">

### Graduate Transcript:

</p>

<p style="margin-top: 20px;">

##### Spring 2025

</p>

BIOL 604: Research Integrity

ENVS 603 Environmental Research Methods

ENVS 654: Environmental Remote Sensing

ENVS 625: Spatial Database Management and GIS Modelling

ENVS 693: Internship in Environmental Studies

##### Fall 2024

ENVS 543: Environmental Data Literacy

ENVS 601: Surveys in Environmental Studies

URSP 523: GIS for Land Use and Transportation Planning

##### Spring 2024

ENVS 591 Conference Preparation

ENVS 591 Environmental Risk Communication

ENVS 627: Infographics

ENVS 693: Environmental Studies Internship

------------------------------------------------------------------------

### Undergraduate Transcript:

<p style="margin-top: 20px;">

#### Institutional Credits:

</p>

<p style="margin-top: 20px;">

##### Fall 2023

</p>

ENVS 321: Cartography

ENVS 491: Environmental Studies Preceptor

ENVS 492: Independent Study

ENVS 493: Environmental Studies Internship

ENVS 591: Applied Wetland Ecology

##### Spring 2023

ENGL 310: Professional Writing

ENVS 300: Sustainable Societies: James River

ENVS 355: Water

ENVS 401 Meteorology and Climatology

ENVS 491: Invasive Species Management in Urban Parks

##### Fall 2022

BIOL 307: Aquatic Ecology

ECON 325: Environmental Economics

ENVS 330: Environmental Pollution

ENVS 491: Environmental Studies Preceptor

ENVS 521: Introduction to Geographic Information Systems

INSC 201: Energy

##### Spring2022

BIOL 317: Ecology

ENVS 311: Politics of the Environment

ENVS 343: Data Literacy

ENVS 591: Swift Water Safety

PHYS 201: General Physics I

##### Fall 2021

BIOL 152: Introduction to Biological Science II

BIOZ 152: Introduction to Biological Science Lab II

ENGL 250: Reading Film

ENVS 105: Physical Geology

STAT 210: Basic Practice of Statistics

UNIV 200: Inquiry and Craft of Argument

##### Spring 2021

BIOL 151: Introduction to Biological Science I

BIOZ 151: Introduction to Biological Science Lab I

CHEM 102: General Chemistry II

CHEZ 102: General Chemistry Lab II

ENVS 102: Environmental Studies II

UNIV: 112: Focused Inquiry II

##### Fall 2020

CHEM 101: General Chemistry I

CHEZ: 101 General Chemistry Lab I

ENVS 101: Environmental Studies I

ENVS 222: Electronic Portfolios

MATH 151: Precalculus Math

UNI 111: Focused Inquiry

#### Transfer Credits:

SPAN 1XX: Spanish Transfer Elective

SPAN 205: Intermediate Spanish Conversation

POLI 103: U.S. Government

POLI 1XX: PLS 212 - Government
